# Generated by Django 3.0.5 on 2020-04-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='lavori',
            field=models.CharField(choices=[('datascience', 'DataScience'), ('productowner', 'ProductOwner'), ('businessanalyst', 'BusinessAnalyst')], default=True, max_length=20),
        ),
    ]
