# Generated by Django 3.0.5 on 2020-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questions_lavori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='lavori',
        ),
    ]
