# Generated by Django 3.0.5 on 2020-05-04 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_questions_lavori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
