# Generated by Django 3.0.5 on 2020-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.TextField(max_length=20)),
                ('descrizione', models.TextField(max_length=20)),
                ('requisiti', models.TextField(max_length=20)),
            ],
        ),
    ]
