# Generated by Django 3.0.5 on 2020-04-21 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='company',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
