# Generated by Django 3.0.5 on 2020-04-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200423_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='student',
        ),
    ]
