# Generated by Django 3.0.5 on 2020-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200425_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_job',
            name='email_referente',
            field=models.CharField(default='inserisci email', max_length=20),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='nome_azienda',
            field=models.CharField(default=' inserisci nome', max_length=20),
        ),
    ]
