# Generated by Django 3.0.5 on 2020-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200425_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='Categoria',
            field=models.CharField(default='inserisci categoria', max_length=20),
        ),
    ]
