# Generated by Django 3.0.5 on 2020-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_post_job_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='Categoria',
        ),
    ]
